### ISSUE TITLE
No Modules named wallet.tool

### ISSUE THREAD

**Issue by Starblue0** [akx/walletool#20]
Running on my m1 Macbook pro OSX 12.5. 

Gives a Modules not found error. tested on Python 2.7 and python 3.9 and same error.

<img width="560" alt="Screen Shot 2022-08-03 at 10 16 39 AM" src="https://user-images.githubusercontent.com/89170602/182645501-dd15f3b8-f61d-4938-bb34-cc2165c2cda9.png">
 

Please help :)

**Comment by Starblue0** [comment]
i moved the files from wallet tool to walletool-master and i got this error now. 

<img width="562" alt="Screen Shot 2022-08-03 at 10 27 50 AM" src="https://user-images.githubusercontent.com/89170602/182647495-a312b664-59bd-4065-987d-dcbd4548ca11.png">

**Comment by akx** [comment]
You shouldn't be moving any files around for this to work.

You also _really_ shouldn't be running as root.

In the second screenshot, you're using Python 2. That won't work.
