### ISSUE TITLE
help me for error -h and -v

### ISSUE THREAD

**Issue by erkamim** [akx/walletool#6]
D:\walletool-master>wt_extract_keys.py -d wallet.dat -v 0
usage: wt_extract_keys.py [-h] -d FILENAME -v VERSION
wt_extract_keys.py: error: the following arguments are required: -d/--dat, -v/--
version
help me sir, 
when I run it appears an error

**Comment by akx** [comment]
Try `python wt_extract_keys.py ...` instead?

**Comment by erkamim** [comment]
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Windows\system32>d:

D:\>cd walletool-master

D:\walletool-master>dir
 Volume in drive D has no label.
 Volume Serial Number is DF14-C670

 Directory of D:\walletool-master

29/05/2020  21:37    <DIR>          .
29/05/2020  21:37    <DIR>          ..
29/05/2020  21:25    <DIR>          .github
04/03/2020  13:59                40 .gitignore
04/03/2020  13:59             1.011 check_bchain.py
04/03/2020  13:59               872 check_dogechain.py
04/03/2020  13:59               564 README.md
29/05/2020  21:25    <DIR>          testdata
23/05/2020  06:28            73.728 wallet.dat
29/05/2020  21:33    <DIR>          walletool
04/03/2020  13:59             1.250 wt_extract_keys.py
               6 File(s)         77.465 bytes
               5 Dir(s)  159.406.862.336 bytes free

D:\walletool-master>python wt_extract_keys.py -d wallet.dat -v 0
'python' is not recognized as an internal or external command,
operable program or batch file.

D:\walletool-master>wt_extract_keys.py -d wallet.dat -v 0
usage: wt_extract_keys.py [-h] -d FILENAME -v VERSION
wt_extract_keys.py: error: the following arguments are required: -d/--dat, -v/--
version

D:\walletool-master>python wt_extract_keys.py -d wallet.dat -v 0
'python' is not recognized as an internal or external command,
operable program or batch file.

D:\walletool-master>
![2020-05-29_234039](https://user-images.githubusercontent.com/55318006/83283864-1855c880-a206-11ea-95b3-4640c78491b8.png)


same is still an error, sir

**Comment by akx** [comment]
Ah, `python` is not on your PATH.

Depending on how you've installed Python, it may use the `py` launcher instead. You may also try and look for `python.exe` and run something like `c:\that\path\python.exe wt_extract_keys.py ...`

**Comment by erkamim** [comment]
> Ah, `python` is not on your PATH.
> 
> Depending on how you've installed Python, it may use the `py` launcher instead. You may also try and look for `python.exe` and run something like `c:\that\path\python.exe wt_extract_keys.py ...`

**Comment by erkamim** [comment]
setelah itu saya jalankan tapi belum ada hasil ,

![2020-05-30_102629](https://user-images.githubusercontent.com/55318006/83318582-541d7c00-a260-11ea-9fda-d86d690485c4.png)

i check in testdata btc.txt also not yet there

**Comment by erkamim** [comment]
> setelah itu saya jalankan tapi belum ada hasil ,
> 
> ![2020-05-30_102629](https://user-images.githubusercontent.com/55318006/83318582-541d7c00-a260-11ea-9fda-d86d690485c4.png)
> 
> i check in testdata btc.txt also not yet there

![2020-05-30_102930](https://user-images.githubusercontent.com/55318006/83318619-b4142280-a260-11ea-942b-e24e5048e397.png)
help me please sir

**Comment by erkamim** [comment]
> setelah itu saya jalankan tapi belum ada hasil ,
> 
> ![2020-05-30_102629](https://user-images.githubusercontent.com/55318006/83318582-541d7c00-a260-11ea-9fda-d86d690485c4.png)
> 
> i check in testdata btc.txt also not yet there

after that I ran it but there was no result

**Comment by akx** [comment]
If there's no output, then the program was unable to extract any keys.

Encrypted wallets are not supported, sorry.
