### ISSUE TITLE
to check the location of the results where

### ISSUE THREAD

**Issue by erkamim** [akx/walletool#7]
after that I ran it but there was no result
![2020-05-30_102629](https://user-images.githubusercontent.com/55318006/83319004-7b764800-a264-11ea-8fee-cc03c1f6a74d.png)
![2020-05-30_102930](https://user-images.githubusercontent.com/55318006/83319006-8335ec80-a264-11ea-90db-231dc086e8a8.png)

help me sir, thanks

**Comment by akx** [comment]
If there's no output, then the program was unable to extract any keys.

Encrypted wallets are not supported, sorry.
