### ISSUE TITLE
Result

### ISSUE THREAD

**Issue by ashraful1980** [akx/walletool#8]
The script has been run yet, But no result has been found or output was found empty....

**Comment by ashraful1980** [comment]
Sir,
Install Python 3.x. along with bsddb3 for windows. Please confirm which version install on python; I have run with the script from 3.7.0. The result was not published. Attached herewith screenshot for your kind reference.
![image](https://user-images.githubusercontent.com/52574658/85520964-6acbae80-b625-11ea-81cf-b0eaa831a113.png)

Also you have published on test data as attached.
![image](https://user-images.githubusercontent.com/52574658/85521524-2c82bf00-b626-11ea-843a-70da063c9fc2.png)


So please advice how it is run.....

**Comment by ashraful1980** [comment]
Note that the wallet.dat is old version... Encrypted wallet.....

**Comment by akx** [comment]
If there's no output, then the program was unable to extract any keys.

Encrypted wallets are not supported, sorry.

**Comment by ashraful1980** [comment]
Thank you for your quick response. 

I have request please develop script for extracting Encrypted wallets..... Also if you have already develop; please give me a script following email id: ashraf.csr@gmail.com

Thanks,
Ashraf

**Comment by akx** [comment]
It's not possible to extract keys from an encrypted wallet without knowing or cracking the passphrase.
