### ISSUE TITLE
checksum error 

### ISSUE THREAD

**Issue by mikejnpc** [akx/walletool#9]
\Python36\walletool-master\walletool\wallet_files.py", line 16, in read_wallet_dat
    d.open(filename, 'main', db.DB_BTREE, db.DB_THREAD | db.DB_RDONLY)
bsddb3.db.DBInvalidArgError: (22, 'Invalid argument -- BDB0210 E:\\Python36\\walletool-master\\R.DAT: metadata page checksum error')

reason there is  a checksum error?

**Comment by isp** [comment]
I am getting this error as well 

`  File "/mnt/c/Users/jon/Documents/walletool-master/walletool/wallet_files.py", line 16, in read_wallet_dat
    d.open(filename, 'main', db.DB_BTREE, db.DB_THREAD | db.DB_RDONLY)
bsddb3.db.DBInvalidArgError: (22, 'Invalid argument -- BDB0210 /mnt/c/Users/jon/Documents/walletool-master/wallet.dat: metadata page checksum error')`

**Comment by akx** [comment]
This sounds like the file is corrupted.

Since `wallet.dat` is a BerkeleyDB file, you could attempt using the [`db_dump`](https://www.manpagez.com/man/1/db_dump/) utility's `-r` option for recovery; something like

```
cp wallet.dat wallet.dat.bak  # grab a backup
db_dump -r wallet.dat | db_load wallet-recovered.dat
```
and then use Walletool as usual.

**Comment by hmt1027** [comment]
Traceback (most recent call last):
  File "wt_extract_keys.py", line 2, in <module>
    from walletool.wallet_files import read_wallet_dat
ImportError: No module named walletool.wallet_files
